import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === "production";

// Target Obsidian vault plugin directory
const VAULT_PLUGIN_DIR = "D:/Note/obsidian/_CyrusH/.obsidian/plugins/synobsidian";

/** Copy built files to the Obsidian vault plugins directory. */
function copyToVault() {
  if (!fs.existsSync(VAULT_PLUGIN_DIR)) {
    console.log(`[deploy] Vault plugin dir not found, skipping copy: ${VAULT_PLUGIN_DIR}`);
    return;
  }
  const files = ["main.js", "manifest.json", "styles.css"];
  for (const file of files) {
    const src = path.join(process.cwd(), file);
    const dest = path.join(VAULT_PLUGIN_DIR, file);
    if (fs.existsSync(src)) {
      fs.copyFileSync(src, dest);
      console.log(`[deploy] Copied ${file} → vault`);
    }
  }
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [
    {
      name: "deploy-to-vault",
      setup(build) {
        build.onEnd(() => copyToVault());
      },
    },
  ],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
